### ISSUE TITLE
HI, what about 8 classes classification?

### ISSUE THREAD

**Issue by Lym2333** [Zyad-Abdelhafiz/Eye-Diseases-Using-Fundus#1]
i'm confused what's the keywords? 
cataract 's keyword is cataract, but dr or amd ' s keywords are not like that.

**Comment by Zyad-Abdelhafiz** [comment]
8 classes classification keywords that are already mentioned

<img width="475" alt="Screenshot 2023-03-02 at 9 14 24 PM" src="https://user-images.githubusercontent.com/96571298/222516442-77907f1c-5141-408f-bd10-829954528d20.png">

There are no other keywords such as 
- **dr** 
-  **amd.**
